apiVersion: v1
kind: Service
metadata:
  name: inventory-service-service
  namespace: warehousing
  labels:
    app: inventory-service
    domain: warehousing
spec:
  selector:
    app: inventory-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
