version = 1

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "17"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  style_guide = "standard"
  dialect = "typescript"

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "google-java-format"
enabled = true
