apiVersion: v1
kind: Service
metadata:
  name: warehouse-analytics-service
  namespace: warehousing
  labels:
    app: warehouse-analytics
    domain: warehousing
spec:
  selector:
    app: warehouse-analytics
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
