apiVersion: v1
kind: Service
metadata:
  name: fulfillment-service-service
  namespace: warehousing
  labels:
    app: fulfillment-service
    domain: warehousing
spec:
  selector:
    app: fulfillment-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
